-- Database generated with pgModeler (PostgreSQL Database Modeler).
-- pgModeler  version: 0.9.2
-- PostgreSQL version: 12.0
-- Project Site: pgmodeler.io
-- Model Author: ---


-- Database creation must be done outside a multicommand file.
-- These commands were put in this file only as a convenience.
-- -- object: smp_aid | type: DATABASE --
-- -- DROP DATABASE IF EXISTS smp_aid;
-- CREATE DATABASE smp_aid;
-- -- ddl-end --
-- 

-- object: public.receivers | type: TABLE --
-- DROP TABLE IF EXISTS public.receivers CASCADE;
CREATE TABLE public.receivers (
	id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ,
	inn text,
	name text,
	CONSTRAINT subjects_ul_pk PRIMARY KEY (id)

);
-- ddl-end --
-- ALTER TABLE public.receivers OWNER TO postgres;
-- ddl-end --

-- object: public.aids | type: TABLE --
-- DROP TABLE IF EXISTS public.aids CASCADE;
CREATE TABLE public.aids (
	id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ,
	aid_term date,
	aid_start_date date,
	aid_end_date date,
	aid_size float,
	aid_size_measure smallint,
	aid_is_breach bool,
	aid_is_misaimed bool,
	receiver integer,
	subject_type smallint,
	subject_category smallint,
	aid_form integer,
	aid_kind integer,
	gov_body integer,
	CONSTRAINT aids_pk PRIMARY KEY (id)

);
-- ddl-end --
-- ALTER TABLE public.aids OWNER TO postgres;
-- ddl-end --

-- object: receivers_fk | type: CONSTRAINT --
-- ALTER TABLE public.aids DROP CONSTRAINT IF EXISTS receivers_fk CASCADE;
ALTER TABLE public.aids ADD CONSTRAINT receivers_fk FOREIGN KEY (receiver)
REFERENCES public.receivers (id) MATCH FULL
ON DELETE SET NULL ON UPDATE CASCADE;
-- ddl-end --

-- object: public.subject_types | type: TABLE --
-- DROP TABLE IF EXISTS public.subject_types CASCADE;
CREATE TABLE public.subject_types (
	id smallint NOT NULL GENERATED BY DEFAULT AS IDENTITY ,
	name text,
	CONSTRAINT subject_types_pk PRIMARY KEY (id)

);
-- ddl-end --
-- ALTER TABLE public.subject_types OWNER TO postgres;
-- ddl-end --

-- object: subject_types_fk | type: CONSTRAINT --
-- ALTER TABLE public.aids DROP CONSTRAINT IF EXISTS subject_types_fk CASCADE;
ALTER TABLE public.aids ADD CONSTRAINT subject_types_fk FOREIGN KEY (subject_type)
REFERENCES public.subject_types (id) MATCH FULL
ON DELETE SET NULL ON UPDATE CASCADE;
-- ddl-end --

-- object: public.subject_categories | type: TABLE --
-- DROP TABLE IF EXISTS public.subject_categories CASCADE;
CREATE TABLE public.subject_categories (
	id smallint NOT NULL GENERATED BY DEFAULT AS IDENTITY ,
	name text,
	CONSTRAINT subject_types_pk_1 PRIMARY KEY (id)

);
-- ddl-end --
-- ALTER TABLE public.subject_categories OWNER TO postgres;
-- ddl-end --

-- object: subject_categories_fk | type: CONSTRAINT --
-- ALTER TABLE public.aids DROP CONSTRAINT IF EXISTS subject_categories_fk CASCADE;
ALTER TABLE public.aids ADD CONSTRAINT subject_categories_fk FOREIGN KEY (subject_category)
REFERENCES public.subject_categories (id) MATCH FULL
ON DELETE SET NULL ON UPDATE CASCADE;
-- ddl-end --

-- object: public.aid_forms | type: TABLE --
-- DROP TABLE IF EXISTS public.aid_forms CASCADE;
CREATE TABLE public.aid_forms (
	id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ,
	name text,
	CONSTRAINT iad_form_pk PRIMARY KEY (id)

);
-- ddl-end --
-- ALTER TABLE public.aid_forms OWNER TO postgres;
-- ddl-end --

-- object: aid_forms_fk | type: CONSTRAINT --
-- ALTER TABLE public.aids DROP CONSTRAINT IF EXISTS aid_forms_fk CASCADE;
ALTER TABLE public.aids ADD CONSTRAINT aid_forms_fk FOREIGN KEY (aid_form)
REFERENCES public.aid_forms (id) MATCH FULL
ON DELETE SET NULL ON UPDATE CASCADE;
-- ddl-end --

-- object: public.aid_kinds | type: TABLE --
-- DROP TABLE IF EXISTS public.aid_kinds CASCADE;
CREATE TABLE public.aid_kinds (
	id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ,
	name text,
	CONSTRAINT aid_kinds_pk PRIMARY KEY (id)

);
-- ddl-end --
-- ALTER TABLE public.aid_kinds OWNER TO postgres;
-- ddl-end --

-- object: aid_kinds_fk | type: CONSTRAINT --
-- ALTER TABLE public.aids DROP CONSTRAINT IF EXISTS aid_kinds_fk CASCADE;
ALTER TABLE public.aids ADD CONSTRAINT aid_kinds_fk FOREIGN KEY (aid_kind)
REFERENCES public.aid_kinds (id) MATCH FULL
ON DELETE SET NULL ON UPDATE CASCADE;
-- ddl-end --

-- object: public.gov_bodies | type: TABLE --
-- DROP TABLE IF EXISTS public.gov_bodies CASCADE;
CREATE TABLE public.gov_bodies (
	id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ,
	inn text,
	name text,
	CONSTRAINT gov_bodies_pk PRIMARY KEY (id)

);
-- ddl-end --
-- ALTER TABLE public.gov_bodies OWNER TO postgres;
-- ddl-end --

-- object: gov_bodies_fk | type: CONSTRAINT --
-- ALTER TABLE public.aids DROP CONSTRAINT IF EXISTS gov_bodies_fk CASCADE;
ALTER TABLE public.aids ADD CONSTRAINT gov_bodies_fk FOREIGN KEY (gov_body)
REFERENCES public.gov_bodies (id) MATCH FULL
ON DELETE SET NULL ON UPDATE CASCADE;
-- ddl-end --


